name: Referral
version: 2.2.5
api-version: 1.13
author: Teenaapje
main: me.teenaapje.referral.ReferralCore
description: Referral
softdepend: [PlaceholderAPI]
commands:
    Ref:
        description: /Ref to get more options
